import { describe, expect, test, mock, spyOn, afterEach } from 'bun:test';

const mockFetchTranscript = mock(() =>
  Promise.resolve({
    videoId: 'vid-123',
    language: 'ko',
    isAutoGenerated: true,
    segments: [
      { text: '안녕하세요', start: 0, duration: 3 },
      { text: '테스트입니다', start: 3, duration: 2 },
    ],
  }),
);

mock.module('../transcript', () => ({ fetchTranscript: mockFetchTranscript }));

describe('dataTranscriptAction', () => {
  let consoleSpy: ReturnType<typeof spyOn>;

  afterEach(() => {
    consoleSpy?.mockRestore();
    mockFetchTranscript.mockClear();
  });

  test('videoId를 전달하여 fetchTranscript을 호출한다', async () => {
    consoleSpy = spyOn(console, 'log').mockImplementation(() => {});
    const { dataTranscriptAction } = await import('./data-transcript');

    await dataTranscriptAction({} as never, {
      format: 'json',
      videoId: 'vid-123',
    });

    expect(mockFetchTranscript).toHaveBeenCalledWith('vid-123', undefined);
  });

  test('lang 옵션을 전달한다', async () => {
    consoleSpy = spyOn(console, 'log').mockImplementation(() => {});
    const { dataTranscriptAction } = await import('./data-transcript');

    await dataTranscriptAction({} as never, {
      format: 'json',
      videoId: 'vid-123',
      lang: 'en',
    });

    expect(mockFetchTranscript).toHaveBeenCalledWith('vid-123', 'en');
  });

  test('json 포맷으로 결과를 출력한다', async () => {
    consoleSpy = spyOn(console, 'log').mockImplementation(() => {});
    const { dataTranscriptAction } = await import('./data-transcript');

    await dataTranscriptAction({} as never, {
      format: 'json',
      videoId: 'vid-123',
    });

    expect(consoleSpy).toHaveBeenCalled();
    const printed = consoleSpy.mock.calls[0][0] as string;
    const parsed = JSON.parse(printed);
    expect(parsed.videoId).toBe('vid-123');
    expect(parsed.segments).toHaveLength(2);
  });

  test('text 포맷으로 순수 텍스트만 출력한다', async () => {
    consoleSpy = spyOn(console, 'log').mockImplementation(() => {});
    const { dataTranscriptAction } = await import('./data-transcript');

    await dataTranscriptAction({} as never, {
      format: 'text',
      videoId: 'vid-123',
    });

    expect(consoleSpy).toHaveBeenCalled();
    const printed = consoleSpy.mock.calls[0][0] as string;
    expect(printed).toBe('안녕하세요\n테스트입니다');
  });
});
