export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  baseUrl: string;
  kind: string | undefined;
}

export interface TranscriptResult {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

interface InnertubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InnertubeTrack[];
    };
  };
}

interface InnertubeTrack {
  baseUrl: string;
  name: { simpleText: string };
  languageCode: string;
  kind?: string;
}

const INNERTUBE_URL = 'https://www.youtube.com/youtubei/v1/player';

const INNERTUBE_CONTEXT = {
  client: {
    clientName: 'WEB',
    clientVersion: '2.20240101.00.00',
  },
};

export function extractCaptionTracks(playerResponse: Record<string, unknown>): CaptionTrack[] {
  const captions = playerResponse.captions as InnertubePlayerResponse['captions'] | undefined;
  const tracks = captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks) return [];

  return tracks.map((track) => ({
    languageCode: track.languageCode,
    name: track.name.simpleText,
    baseUrl: track.baseUrl,
    kind: track.kind,
  }));
}

export function selectTrack(tracks: CaptionTrack[], lang?: string): CaptionTrack {
  if (tracks.length === 0) {
    throw new Error('No caption tracks available for this video');
  }

  if (lang) {
    const found = tracks.find((t) => t.languageCode === lang);
    if (!found) {
      const available = tracks.map((t) => t.languageCode).join(', ');
      throw new Error(`Language '${lang}' not found. Available: ${available}`);
    }
    return found;
  }

  return tracks[0];
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#(\d+);/g, (_match, code) => String.fromCharCode(parseInt(code, 10)));
}

export function parseTimedTextXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const regex = /<text\s+start="([^"]*?)"\s+dur="([^"]*?)"[^>]*>([\s\S]*?)<\/text>/g;

  let match: RegExpExecArray | null;
  while ((match = regex.exec(xml)) !== null) {
    segments.push({
      start: parseFloat(match[1]),
      duration: parseFloat(match[2]),
      text: decodeHtmlEntities(match[3]),
    });
  }

  return segments;
}

async function fetchPlayerResponse(videoId: string): Promise<InnertubePlayerResponse> {
  const response = await fetch(INNERTUBE_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      context: INNERTUBE_CONTEXT,
      videoId,
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch player response: ${response.status}`);
  }

  return (await response.json()) as InnertubePlayerResponse;
}

async function fetchTimedText(trackUrl: string): Promise<string> {
  const response = await fetch(trackUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch timed text: ${response.status}`);
  }
  return response.text();
}

export async function fetchTranscript(videoId: string, lang?: string): Promise<TranscriptResult> {
  const playerResponse = await fetchPlayerResponse(videoId);
  const tracks = extractCaptionTracks(playerResponse as Record<string, unknown>);

  if (tracks.length === 0) {
    throw new Error(`No captions available for video: ${videoId}`);
  }

  const track = selectTrack(tracks, lang);
  const xml = await fetchTimedText(track.baseUrl);
  const segments = parseTimedTextXml(xml);

  return {
    videoId,
    language: track.languageCode,
    isAutoGenerated: track.kind === 'asr',
    segments,
  };
}

export async function listAvailableTracks(videoId: string): Promise<CaptionTrack[]> {
  const playerResponse = await fetchPlayerResponse(videoId);
  return extractCaptionTracks(playerResponse as Record<string, unknown>);
}
