import { execFile } from 'node:child_process';

function execFileAsync(
  cmd: string,
  args: string[],
  opts: { timeout?: number; maxBuffer?: number },
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(cmd, args, opts, (err, stdout, stderr) => {
      if (err) return reject(err);
      resolve({ stdout, stderr });
    });
  });
}

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  baseUrl: string;
  kind: string | undefined;
}

export interface TranscriptResult {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
}

interface Json3Response {
  events?: Json3Event[];
}

interface SubtitleFormat {
  ext: string;
  url: string;
}

interface YtDlpDumpJson {
  subtitles?: Record<string, SubtitleFormat[]>;
  automatic_captions?: Record<string, SubtitleFormat[]>;
}

const YT_DLP_TIMEOUT_MS = 30_000;

async function runYtDlp(args: string[]): Promise<string> {
  try {
    const { stdout } = await execFileAsync('yt-dlp', args, {
      timeout: YT_DLP_TIMEOUT_MS,
      maxBuffer: 10 * 1024 * 1024,
    });
    return stdout;
  } catch (err: unknown) {
    if (err && typeof err === 'object' && 'code' in err && err.code === 'ENOENT') {
      throw new Error(
        'yt-dlp is not installed. Install it: https://github.com/yt-dlp/yt-dlp#installation',
      );
    }
    throw err;
  }
}

function findJson3Url(formats: SubtitleFormat[]): string | undefined {
  return formats.find((f) => f.ext === 'json3')?.url;
}

function buildTracksFromDumpJson(dumpJson: YtDlpDumpJson): CaptionTrack[] {
  const tracks: CaptionTrack[] = [];

  const subs = dumpJson.subtitles ?? {};
  for (const [lang, formats] of Object.entries(subs)) {
    const json3Url = findJson3Url(formats) ?? '';
    tracks.push({
      languageCode: lang,
      name: lang,
      baseUrl: json3Url,
      kind: undefined,
    });
  }

  const auto = dumpJson.automatic_captions ?? {};
  for (const [lang, formats] of Object.entries(auto)) {
    if (subs[lang]) continue;
    const json3Url = findJson3Url(formats) ?? '';
    tracks.push({
      languageCode: lang,
      name: `${lang} (auto)`,
      baseUrl: json3Url,
      kind: 'asr',
    });
  }

  return tracks;
}

export function parseJson3Subtitles(json3: Json3Response): TranscriptSegment[] {
  const events = json3.events ?? [];
  const segments: TranscriptSegment[] = [];

  for (const event of events) {
    if (!event.segs || event.segs.length === 0) continue;

    const text = event.segs.map((s) => s.utf8 ?? '').join('');
    segments.push({
      text,
      start: (event.tStartMs ?? 0) / 1000,
      duration: (event.dDurationMs ?? 0) / 1000,
    });
  }

  return segments;
}

export function selectTrack(tracks: CaptionTrack[], lang?: string): CaptionTrack {
  if (tracks.length === 0) {
    throw new Error('No caption tracks available for this video');
  }

  if (lang) {
    const found = tracks.find((t) => t.languageCode === lang);
    if (!found) {
      const available = tracks.map((t) => t.languageCode).join(', ');
      throw new Error(`Language '${lang}' not found. Available: ${available}`);
    }
    return found;
  }

  return tracks[0];
}

async function fetchDumpJson(videoId: string): Promise<YtDlpDumpJson> {
  const stdout = await runYtDlp([
    '--dump-json',
    '--skip-download',
    `https://www.youtube.com/watch?v=${videoId}`,
  ]);
  return JSON.parse(stdout) as YtDlpDumpJson;
}

export async function fetchTranscript(videoId: string, lang?: string): Promise<TranscriptResult> {
  const dumpJson = await fetchDumpJson(videoId);
  const tracks = buildTracksFromDumpJson(dumpJson);

  if (tracks.length === 0) {
    throw new Error(`No captions available for video: ${videoId}`);
  }

  const track = selectTrack(tracks, lang);

  const isAuto = track.kind === 'asr';
  const source = isAuto
    ? dumpJson.automatic_captions ?? {}
    : dumpJson.subtitles ?? {};
  const formats = source[track.languageCode];
  const json3Url = formats ? findJson3Url(formats) : undefined;

  if (!json3Url) {
    throw new Error(`No json3 subtitle format available for language: ${track.languageCode}`);
  }

  const response = await fetch(json3Url);
  if (!response.ok) {
    throw new Error(`Failed to fetch subtitle data: ${response.status}`);
  }

  const json3Data = (await response.json()) as Json3Response;
  const segments = parseJson3Subtitles(json3Data);

  return {
    videoId,
    language: track.languageCode,
    isAutoGenerated: isAuto,
    segments,
  };
}

export async function listAvailableTracks(videoId: string): Promise<CaptionTrack[]> {
  const dumpJson = await fetchDumpJson(videoId);
  return buildTracksFromDumpJson(dumpJson);
}
